/**
 * teacherModules.js — Content configuration for the four teacher dedicated pages.
 * Mirrors the shape of studentModules.js. Each key matches the page slug.
 */

export const TEACHER_MODULES = {
  "how-it-helps": {
    slug: "how-it-helps",
    path: "/teachers/how-it-helps",
    navLabel: "How It Helps",
    docTitle: "How It Helps — Classess.com® Teacher",
    metaDescription:
      "Discover how Classess.com® improves teaching by connecting planning, assessment, feedback, and student support into one academic journey.",
    heading: "Better support for every stage of teaching.",
    intro: [
      "Classess.com® connects planning, classroom learning, assessment, feedback, student support, and progress into one academic journey—helping teachers work with greater clarity and respond to students more effectively.",
    ],
    outcomes: [
      { title: "Improve your teaching", body: "Understand how Classess.com® reduces repetitive work so you have more time for meaningful teaching and student interaction." },
      { title: "Reduce repetitive work", body: "Spend less time on preparation, grading, and admin—while maintaining the quality and context of your academic outputs." },
      { title: "Understand students better", body: "See where each student is succeeding and where support is required, using real learning evidence." },
      { title: "Support better decisions", body: "Move from gut feel to informed academic decisions grounded in clear evidence and structured insights." },
      { title: "AI that assists, not replaces", body: "AI-supported outputs can be reviewed, edited, approved, or rejected before reaching students—teacher judgement stays central." },
      { title: "Independent or institution-connected", body: "Use Classess.com® as an independent teacher or within your institution's curriculum, policies, and reporting structures." },
    ],
    sections: [
      {
        id: "connected-teaching-journey",
        kind: "flow",
        heading: "A Connected Teaching Journey",
        intro: "Teaching does not happen in disconnected steps. A lesson plan influences classroom learning. Classroom learning influences assessment. Assessment reveals student needs. Those needs should guide feedback, intervention, and the next lesson.",
        copy: "Classess.com® connects these stages so teachers can move from activity to insight and from insight to meaningful action.",
        steps: ["Plan", "Teach", "Assess", "Understand", "Support", "Improve"],
      },
      {
        kind: "list",
        heading: "More Time for Meaningful Teaching",
        intro: "Reduce repetitive work without reducing teacher involvement. Classess.com® can support the preparation of lesson drafts, resources, questions, rubrics, feedback, reports, and learning recommendations. Teachers remain responsible for reviewing, editing, approving, and applying these academic outputs.",
        items: [
          "Less time starting from a blank page",
          "More consistent academic preparation",
          "Faster access to usable teaching resources",
          "Reduced repetitive assessment work",
          "More time for student interaction and support",
        ],
      },
      {
        kind: "list",
        heading: "Better Visibility into Learning",
        intro: "Understand what students learned—not only what was taught. Classess.com® brings together classroom responses, practice, assignments, assessments, and feedback to help teachers see where students are succeeding and where support is required.",
        items: [
          "Identify misunderstanding earlier",
          "Recognise repeated mistakes",
          "Distinguish non-participation from learning difficulty",
          "Find students ready for further challenge",
          "Make the next lesson more responsive",
        ],
      },
      {
        kind: "list",
        heading: "Support That Matches the Need",
        intro: "Different learning needs require different responses. A student who did not attempt an activity may need a different response from a student who attempted it but struggled with application. Classess.com® helps teachers understand the difference and select more appropriate support.",
        items: [
          "Reteaching",
          "Guided practice",
          "Revision",
          "Remedial learning",
          "Personal feedback",
          "Additional examples",
          "Extension activities",
          "Follow-up assessment",
        ],
      },
      {
        id: "teacher-controlled-ai",
        kind: "list",
        heading: "Teacher-Controlled AI",
        intro: "AI supports professional judgement. It does not replace it. AI-supported outputs can be reviewed, edited, regenerated, approved, or rejected before they are assigned or shared. Teachers continue to shape the learning experience and make the final academic decision.",
        items: [
          "Teacher approval",
          "Editable outputs",
          "Curriculum alignment",
          "Academic context",
          "Transparent recommendations",
          "Responsible student-data use",
          "Role-based permissions",
        ],
      },
      {
        kind: "highlight",
        heading: "Independent or Institution-Connected Use",
        text: "Use Classess.com® independently or through your institution.",
        copy: "Independent teachers and tutors can use available tools for planning, content creation, assessments, feedback, and student support. Institution-connected teachers can additionally work within the curriculum, policies, academic structures, classes, and reporting requirements configured by their institution.",
      },
    ],
    final: {
      heading: "Give every teaching decision better academic context.",
      primary: "Start as a Teacher",
      secondary: "Back to Teacher Home",
    },
  },

  "plan-and-create": {
    slug: "plan-and-create",
    path: "/teachers/plan-and-create",
    navLabel: "Plan & Create",
    docTitle: "Plan & Create — Classess.com® Teacher",
    metaDescription:
      "Learn how Classess.com® helps teachers plan lessons, create academic resources, and prepare classroom-ready learning from curriculum requirements.",
    heading: "Move from curriculum requirements to classroom-ready learning.",
    intro: [
      "Plan lessons, create academic resources, and prepare meaningful learning activities with support that understands the subject, grade, topic, learning outcome, student level, and institutional context.",
    ],
    outcomes: [
      { title: "Faster preparation", body: "Begin with a useful draft rather than a blank page, and spend your time refining the learning experience rather than building it from scratch." },
      { title: "Better curriculum alignment", body: "Connect every lesson, resource, and assessment to the specific curriculum, grade, subject, topic, and learning outcome." },
      { title: "More consistent structure", body: "Create lesson plans and resources that follow a reliable structure—making preparation more efficient and teaching more consistent." },
      { title: "Easier adaptation", body: "Adjust explanations, activities, and questions to meet different learner needs without rebuilding resources from the beginning." },
      { title: "Teacher-controlled output", body: "Review, edit, reorder, and approve all generated material before using it with students. You make the final academic decision." },
      { title: "Reusable teaching library", body: "Save, duplicate, and improve your best lessons and resources over time, building a personal academic library that grows with you." },
    ],
    sections: [
      {
        kind: "highlight",
        heading: "Begin with Academic Context",
        text: "Start with what you are expected to teach.",
        copy: "Select or confirm the curriculum, grade, subject, unit, topic, learning outcome, duration, and student context. Classess.com® uses this information to help prepare more relevant academic material. Teachers spend less time repeatedly entering the same academic context and more time refining the learning experience.",
      },
      {
        kind: "flow",
        heading: "Create Structured Lesson Plans",
        intro: "Begin with a useful draft—not a blank page. Create a lesson or session plan containing appropriate learning objectives, teaching steps, explanations, examples, activities, checks for understanding, resources, and follow-up actions. Teachers can review, edit, reorder, remove, or add content before approval.",
        copy: "The teacher makes every final academic decision before the lesson reaches students.",
        steps: ["Select Context", "Generate Draft", "Review & Edit", "Approve", "Teach"],
      },
      {
        kind: "list",
        heading: "Prepare Classroom Resources",
        intro: "Create the resources your lesson actually needs. Develop supporting academic material connected to the lesson rather than searching through unrelated resources.",
        items: [
          "Explanations",
          "Examples",
          "Classroom activities",
          "Discussion prompts",
          "Visual aids",
          "Worksheets",
          "Assignments",
          "Reading material",
          "Revision activities",
          "Exit questions",
        ],
      },
      {
        kind: "list",
        heading: "Adapt for Different Learners",
        intro: "One classroom does not mean one learning need. Teachers can adapt explanations, activities, questions, and support according to student readiness, learning difficulty, language needs, or required challenge.",
        items: [
          "Simpler explanations where needed",
          "Guided examples for developing learners",
          "Additional practice for identified gaps",
          "Extension work for advanced learners",
          "Multiple ways to approach the same concept",
        ],
      },
      {
        kind: "list",
        heading: "Build Assessments from the Learning",
        intro: "Assess what was intended to be learned. Create questions and assessment activities connected to the topic, learning outcome, skill, difficulty, and expected depth of understanding.",
        items: [
          "Objective questions",
          "Short responses",
          "Descriptive responses",
          "Application questions",
          "Reasoning questions",
          "Rubric-based activities",
          "Practice quizzes",
          "Exit checks",
          "Assignments",
        ],
      },
      {
        kind: "flow",
        heading: "Review Before Use",
        intro: "The teacher makes the final academic decision. Review generated material, make changes, adjust difficulty, replace examples, add institutional requirements, and approve the final version before using it with students.",
        steps: ["Generate", "Review", "Edit", "Approve", "Use"],
      },
      {
        kind: "list",
        heading: "Reuse and Improve",
        intro: "Build on your best academic work. Save, duplicate, adapt, and improve previously created lessons and resources instead of recreating them for every class, section, or academic year.",
        items: [
          "More consistent quality",
          "Less repeated preparation",
          "Easier collaboration",
          "Continuous improvement",
          "Stronger personal teaching library",
        ],
      },
    ],
    final: {
      heading: "Prepare with greater clarity and teach with greater confidence.",
      primary: "Start Planning",
      secondary: "Back to Teacher Home",
    },
  },

  "assess-and-support": {
    slug: "assess-and-support",
    path: "/teachers/assess-and-support",
    navLabel: "Assess & Support",
    docTitle: "Assess & Support — Classess.com® Teacher",
    metaDescription:
      "Learn how Classess.com® helps teachers assess student understanding, provide meaningful feedback, identify learning gaps, and support improvement.",
    heading: "Turn student work into meaningful academic action.",
    intro: [
      "Assess understanding, identify learning needs, provide feedback, assign appropriate support, and review whether students improve.",
    ],
    outcomes: [
      { title: "Assess more than memory", body: "Use different question and activity formats to understand recall, conceptual understanding, application, reasoning, communication, and other relevant academic skills." },
      { title: "More consistent evaluation", body: "Support the review of objective and descriptive work with approved rubrics and marking criteria, while maintaining full teacher oversight." },
      { title: "Feedback students can use", body: "Help students understand what to improve next, not just how they performed. Effective feedback explains what was understood, where difficulty occurred, and what action to take." },
      { title: "Identify who needs support", body: "Distinguish between students who did not attempt, attempted but struggled, repeated the same mistake, improved, or are ready for additional challenge." },
      { title: "Match support to the need", body: "Select or assign a response based on the student's actual learning evidence—not a general assumption about their performance." },
      { title: "Review whether support helped", body: "After intervention, review later practice, assignments, or assessments to understand whether the student improved or requires a different approach." },
    ],
    sections: [
      {
        id: "classroom-understanding",
        kind: "list",
        heading: "Classroom Understanding",
        intro: "Identify confusion while there is still time to respond. Use classroom questions, polls, quizzes, activities, assignments, and short understanding checks to collect learning evidence during and after instruction.",
        items: [
          "See who participated",
          "Find students who are unsure",
          "Identify concepts requiring another explanation",
          "Adjust the pace of teaching",
          "Improve the next lesson",
        ],
      },
      {
        id: "assessment-and-feedback",
        kind: "list",
        heading: "Meaningful Assessment",
        intro: "Assess more than memory. Use different question and activity formats to understand recall, conceptual understanding, application, reasoning, communication, and other relevant academic skills.",
        items: [
          "Curriculum alignment",
          "Difficulty selection",
          "Learning-outcome mapping",
          "Rubrics",
          "Marking schemes",
          "Attempted and unattempted responses",
          "Question-level review",
          "Skill-level understanding",
        ],
      },
      {
        kind: "highlight",
        heading: "More Consistent Evaluation",
        text: "Reduce repetitive review while maintaining teacher oversight.",
        copy: "Classess.com® can support the review of objective and descriptive work, organise response evidence, and apply approved rubrics or marking criteria. Teachers remain responsible for reviewing results and making final decisions, particularly for subjective or high-stakes evaluation.",
      },
      {
        kind: "flow",
        heading: "Feedback Students Can Use",
        intro: "Help students understand what to improve next. Provide feedback through written comments, structured statements, rubrics, or voice where available. Effective feedback should explain what the student understood, where the difficulty occurred, what needs improvement, and what action should be taken next.",
        steps: ["Performance", "Explanation", "Next Action"],
      },
      {
        id: "student-insights",
        kind: "list",
        heading: "Student Insights",
        intro: "See who needs support—and understand why. Classess.com® helps teachers distinguish between different student situations rather than placing every low score into one category.",
        items: [
          "Did not attempt",
          "Attempted but struggled",
          "Repeated the same mistake",
          "Improved after practice",
          "Demonstrated mastery",
          "Ready for additional challenge",
        ],
      },
      {
        kind: "list",
        heading: "Learning Gaps",
        intro: "Move beyond the score to the cause of difficulty. Review topic-level, question-level, concept-level, and skill-level evidence to understand what may be preventing progress.",
        items: [
          "Misunderstood concepts",
          "Weak application",
          "Missing prerequisite knowledge",
          "Repeated process errors",
          "Inconsistent participation",
          "Insufficient practice",
          "Areas requiring revision",
        ],
      },
      {
        kind: "list",
        heading: "Intervention",
        intro: "Match the support to the actual need. Select or assign a response based on the student's learning evidence.",
        items: [
          "Reteach a concept",
          "Share a different explanation",
          "Assign guided practice",
          "Recommend revision",
          "Provide personal feedback",
          "Create a remedial activity",
          "Assign extension work",
          "Schedule a follow-up check",
        ],
      },
      {
        kind: "flow",
        heading: "Review Improvement",
        intro: "Know whether the support made a difference. After intervention, review later practice, assignments, or assessments to understand whether the student improved or requires a different approach.",
        steps: ["Identify", "Support", "Reassess", "Improve"],
      },
    ],
    final: {
      heading: "Make every assessment lead to a better next step.",
      primary: "Start as a Teacher",
      secondary: "Back to Teacher Home",
    },
  },
};

export const TUTORIAL_CATEGORIES = [
  {
    id: "getting-started",
    label: "Getting Started",
    tutorials: [
      { title: "Create a teacher account", desc: "Set up your Classess.com® teacher profile from scratch.", duration: "3 min", level: "Beginner", type: "Video" },
      { title: "Complete the teacher profile", desc: "Add your subjects, grade levels, and teaching preferences.", duration: "4 min", level: "Beginner", type: "Video" },
      { title: "Select curriculum and subjects", desc: "Configure your curriculum context for accurate academic support.", duration: "5 min", level: "Beginner", type: "Video" },
      { title: "Create or join a class", desc: "Set up your first class or connect to an existing institution class.", duration: "4 min", level: "Beginner", type: "Video" },
      { title: "Understand the teacher workspace", desc: "A guided tour of all your teaching tools in one place.", duration: "6 min", level: "Beginner", type: "Video" },
      { title: "Set academic preferences", desc: "Configure default assessment types, feedback styles, and content settings.", duration: "3 min", level: "Beginner", type: "Article" },
    ],
  },
  {
    id: "plan-and-create",
    label: "Plan & Create",
    tutorials: [
      { title: "Create a lesson plan", desc: "Build a structured lesson plan connected to your curriculum.", duration: "7 min", level: "Beginner", type: "Video" },
      { title: "Edit an AI-supported lesson draft", desc: "Review, adjust, and approve a generated lesson plan.", duration: "5 min", level: "Beginner", type: "Video" },
      { title: "Create a worksheet", desc: "Generate and customise a student worksheet for your lesson.", duration: "4 min", level: "Intermediate", type: "Video" },
      { title: "Prepare an assignment", desc: "Build an assignment with objectives, questions, and a rubric.", duration: "6 min", level: "Intermediate", type: "Video" },
      { title: "Generate classroom activities", desc: "Create differentiated classroom activities for a topic.", duration: "5 min", level: "Intermediate", type: "Article" },
      { title: "Adapt content for different learners", desc: "Adjust content difficulty and approach for diverse student needs.", duration: "6 min", level: "Intermediate", type: "Video" },
      { title: "Save and reuse resources", desc: "Organise your teaching library and reuse content across classes.", duration: "4 min", level: "Beginner", type: "Article" },
    ],
  },
  {
    id: "assess-and-evaluate",
    label: "Assess & Evaluate",
    tutorials: [
      { title: "Create an assessment", desc: "Build an assessment from your curriculum context and learning outcomes.", duration: "6 min", level: "Beginner", type: "Video" },
      { title: "Add different question types", desc: "Use objective, short-response, descriptive, and application questions.", duration: "5 min", level: "Intermediate", type: "Video" },
      { title: "Create a rubric", desc: "Design a rubric to evaluate student responses consistently.", duration: "5 min", level: "Intermediate", type: "Video" },
      { title: "Review student responses", desc: "Examine individual and class-level responses for your assessment.", duration: "6 min", level: "Beginner", type: "Video" },
      { title: "Evaluate descriptive answers", desc: "Apply rubrics and provide structured feedback on longer responses.", duration: "7 min", level: "Advanced", type: "Video" },
      { title: "Provide voice feedback", desc: "Record and send voice feedback to students where supported.", duration: "4 min", level: "Intermediate", type: "Video" },
      { title: "Review attempted and unattempted work", desc: "Identify who completed the work and who may need a follow-up.", duration: "4 min", level: "Beginner", type: "Article" },
    ],
  },
  {
    id: "student-insights-support",
    label: "Student Insights & Support",
    tutorials: [
      { title: "Identify learning gaps", desc: "Use evidence from assessments to find concept and skill gaps.", duration: "6 min", level: "Intermediate", type: "Video" },
      { title: "Review class-level insights", desc: "See which topics, concepts, and skills need more attention across your class.", duration: "5 min", level: "Intermediate", type: "Video" },
      { title: "Review an individual student", desc: "Build a complete picture of one student's participation and progress.", duration: "6 min", level: "Intermediate", type: "Video" },
      { title: "Assign remedial work", desc: "Create and send targeted remedial activities to students who need support.", duration: "5 min", level: "Intermediate", type: "Video" },
      { title: "Create targeted practice", desc: "Build practice sets focused on specific identified gaps.", duration: "5 min", level: "Advanced", type: "Video" },
      { title: "Support advanced learners", desc: "Assign extension activities and challenges to students who demonstrate mastery.", duration: "4 min", level: "Intermediate", type: "Article" },
      { title: "Review progress after intervention", desc: "Check whether the support you provided resulted in measurable improvement.", duration: "5 min", level: "Advanced", type: "Video" },
    ],
  },
  {
    id: "teacher-controlled-ai",
    label: "Teacher-Controlled AI",
    tutorials: [
      { title: "Review AI-supported content", desc: "Understand how to evaluate and assess AI-generated academic content.", duration: "5 min", level: "Beginner", type: "Video" },
      { title: "Edit before publishing", desc: "Make targeted edits to drafts before approving for student use.", duration: "4 min", level: "Beginner", type: "Video" },
      { title: "Regenerate selected content", desc: "Request a new version of a section you want to improve.", duration: "3 min", level: "Beginner", type: "Article" },
      { title: "Adjust difficulty", desc: "Modify the level of challenge in AI-generated questions and activities.", duration: "4 min", level: "Intermediate", type: "Video" },
      { title: "Approve and assign", desc: "Complete the final approval step and assign content to students.", duration: "3 min", level: "Beginner", type: "Video" },
      { title: "Report inappropriate or inaccurate output", desc: "Flag and report AI content that does not meet academic standards.", duration: "3 min", level: "Beginner", type: "Article" },
      { title: "Use AI responsibly with students", desc: "Best practices for maintaining teacher authority and student trust.", duration: "6 min", level: "Intermediate", type: "Article" },
    ],
  },
];
